version: '3'
services:
  kafka-mirror-maker-service:
    image: mycompany/kafka
    extra_hosts:
    - "${CONSUMER_BROKER_ADDRESS}"
    - "${PRODUCER_BROKER_ADDRESS}"
    command: "bin/kafka-mirror-maker.sh \
    --consumer.config config/mm_consumer.properties \
    --producer.config config/mm_producer.properties \
    --whitelist=\"${TOPIC_WHITELIST}\""
